name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "ietw.xyz"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "ietw.xyz"

[env.production]
name = "cloudflare-docker-proxy"
 routes = [
   { pattern = "docker.ietw.xyz", custom_domain = true },
   { pattern = "quay.ietw.xyz", custom_domain = true },
   { pattern = "gcr.ietw.xyz", custom_domain = true },
   { pattern = "k8s-gcr.ietw.xyz", custom_domain = true },
   { pattern = "k8s.ietw.xyz", custom_domain = true },
   { pattern = "ghcr.ietw.xyz", custom_domain = true },
   { pattern = "cloudsmith.ietw.xyz", custom_domain = true },
 ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.ietw.xyz", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
